"""
Entry point. Run with:
    uvicorn orchestrator.main:app --host 127.0.0.1 --port 8000 --env-file .env

(drop --reload for the systemd/Render deployment - it's a dev-only convenience)

IMPORTANT - single source of truth: this file IS the API. The files under
startup/routes/ (health.py, strategy.py, ticks.py, telemetry.py) are NOT
imported anywhere below and are dead code relative to what actually runs.
That duplication is exactly what let the wrong GROQ_MODEL default and the
missing statement_cache_size fix go unnoticed for two log cycles - a "fix"
landed in the unused copy while this file kept running the old behavior.

Rather than re-attempt a router split (which is what drifted last time),
the pragmatic fix is the reverse: DELETE startup/routes/*.py from the repo,
or at minimum stop editing them. Every route lives here, once, from now on.
startup/db.py, startup/schemas.py, startup/auth.py, and startup/jobs/* are
still genuinely imported below and remain the real modules for those.

Interactive API docs (Swagger UI) are auto-generated by FastAPI at /docs,
and the raw OpenAPI schema at /openapi.json - no separate Swagger file to
maintain; both stay in sync with this file automatically.
"""
import asyncio
import logging
import os
import re
from contextlib import asynccontextmanager

from apscheduler.schedulers.asyncio import AsyncIOScheduler
from fastapi import Depends, FastAPI, HTTPException, status
from dotenv import load_dotenv

load_dotenv()

from startup.db import close_db_pool, get_pool, init_db_pool
from startup.schemas import HealthOut, StrategyParamsOut, TelemetryIn, TickIn
from startup.jobs.feature_pull import pull_feature_window
from startup.jobs.ml_tier2 import evaluate_tier2_signal
# Single definition of auth lives in startup/auth.py - the local
# `async def verify_api_key(...)` that used to sit here was a second,
# shadowing definition of the same thing (the import was never actually
# used - Python silently let the later def win). Same duplication pattern
# as the routes, just smaller. There is now exactly one.
from startup.auth import verify_api_key

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(name)s: %(message)s")
logger = logging.getLogger("orchestrator")

scheduler = AsyncIOScheduler()

# Groq model IDs are lowercase/hyphenated/slash-namespaced, e.g.
# "openai/gpt-oss-20b". A malformed GROQ_MODEL env var caused every forecast
# cycle to 404 for two full log cycles before anyone noticed, because the
# failure only surfaced 15-30 minutes after startup, inside a background job.
# Fail here instead, before the app accepts any traffic.
_VALID_MODEL_PATTERN = re.compile(r"^[a-z0-9]+(-[a-z0-9]+)*(/[a-z0-9]+(-[a-z0-9]+)*)*$")


def validate_groq_model() -> str:
    model = os.environ.get("GROQ_MODEL", "openai/gpt-oss-20b")
    if not _VALID_MODEL_PATTERN.match(model):
        raise RuntimeError(
            f"GROQ_MODEL='{model}' doesn't look like a valid Groq model id "
            f"(expected lowercase/hyphenated, e.g. 'openai/gpt-oss-20b'). Check .env."
        )
    logger.info("Using Groq model: %s", model)
    return model


@asynccontextmanager
async def lifespan(app: FastAPI):
    validate_groq_model()

    # Initialize shared database connection pool
    await init_db_pool()

    try:
        from startup.jobs.groq_forecast import run_forecast_cycle
        from startup.jobs.gatekeeper import run_gatekeeper_cycle
        # auto_tester intentionally NOT imported/scheduled - see
        # auto_tester_review.md. ShutdownTerminal=1 in auto_tester.py's .ini
        # points MT5_PATH at "FBS MetaTrader 5.lnk" on the Public Desktop -
        # the same shortcut the live/demo terminal runs from, not a separate
        # dedicated test install. Re-enable only once MT5_PATH points at a
        # genuinely separate instance that has never logged into the trading
        # account.
        # from startup.jobs.auto_tester import continuous_tester_cycle

        # Schedule background tasks
        scheduler.add_job(run_forecast_cycle, "interval", minutes=15, id="run_forecast_cycle")
        scheduler.add_job(run_gatekeeper_cycle, "interval", hours=1, id="run_gatekeeper_cycle")
        # scheduler.add_job(continuous_tester_cycle, "cron", hour=2, id="continuous_tester_cycle")

        scheduler.start()
        logger.info("APScheduler initialized: Forecast (15m), Gatekeeper (1h). AutoTester DISABLED - see auto_tester_review.md.")
    except Exception as e:
        logger.warning(f"Failed scheduling background jobs: {e}")

    yield

    # Teardown
    scheduler.shutdown(wait=False)
    await close_db_pool()


app = FastAPI(
    title="PROJECT KENJIN - Quant Matrix Orchestrator",
    description="High-frequency EA telemetry, indicator snapshot ingestion, and multi-tier strategy parameter sync API.",
    version="10.0.1",
    lifespan=lifespan,
)


# --- ROUTES ---

@app.get("/health", response_model=HealthOut, tags=["System Health"], summary="Service and Database Health Check")
async def health():
    """
    Deliberately NOT behind API-key auth - v10's OnInit() calls this to
    decide whether to allow trading at all, and it must stay reachable
    even if the key is misconfigured elsewhere.
    """
    try:
        pool = get_pool()
        async with pool.acquire() as conn:
            await conn.fetchval("SELECT 1;")
        return HealthOut(status="ok", db="ok")
    except Exception as exc:
        logger.error(f"Healthcheck DB failure: {exc}")
        raise HTTPException(status_code=status.HTTP_503_SERVICE_UNAVAILABLE, detail=f"Database unreachable: {exc}")


@app.get(
    "/strategy_params",
    response_model=StrategyParamsOut,
    dependencies=[Depends(verify_api_key)],
    tags=["Strategy"],
    summary="Fetch Optimized Parameters & Tier-2 Signals",
)
async def get_strategy_params(asset: str):
    pool = get_pool()
    async with pool.acquire() as conn:
        row = await conn.fetchrow(
            "SELECT asset, opt_threshold, opt_sl_mult, opt_tp_mult, live_approved FROM strategy_db WHERE asset = $1",
            asset,
        )
        if not row:
            raise HTTPException(status_code=404, detail=f"Asset '{asset}' missing in strategy_db.")

        forecast = await conn.fetchrow(
            "SELECT id, bullish_prob, bearish_prob FROM forecasts WHERE asset = $1 ORDER BY generated_at DESC LIMIT 1",
            asset,
        )

    bullish_prob = float(forecast["bullish_prob"]) if forecast and forecast["bullish_prob"] is not None else 50.0
    bearish_prob = float(forecast["bearish_prob"]) if forecast and forecast["bearish_prob"] is not None else 50.0
    opt_threshold = float(row["opt_threshold"]) if row["opt_threshold"] is not None else 0.60

    # Tier-2 is experimental (untrained model, feature-name mismatch against
    # tick_telemetry - see the prior review). It must never be able to take
    # down the one endpoint v10 depends on for basic threshold/SL/TP sync,
    # so a failure here degrades to HOLD/neutral rather than a 500.
    try:
        df = await pull_feature_window(asset, minutes=30)
        tier2 = await asyncio.to_thread(
            evaluate_tier2_signal, df, bullish_prob, bearish_prob, opt_threshold
        )
    except Exception:
        logger.exception("Tier-2 evaluation failed for %s - degrading to HOLD/neutral.", asset)
        tier2 = {"action": "HOLD", "confidence": 0.0, "lot_multiplier": 1.0}

    return StrategyParamsOut(
        asset=row["asset"],
        opt_threshold=opt_threshold,
        opt_sl_mult=float(row["opt_sl_mult"]) if row["opt_sl_mult"] is not None else 1.5,
        opt_tp_mult=float(row["opt_tp_mult"]) if row["opt_tp_mult"] is not None else 3.0,
        live_approved=bool(row["live_approved"]),
        forecast_id=forecast["id"] if forecast else None,
        bullish_prob=bullish_prob,
        bearish_prob=bearish_prob,
        tier2_action=tier2.get("action", "HOLD"),
        tier2_confidence=tier2.get("confidence", 0.0),
        recommended_lot_multiplier=tier2.get("lot_multiplier", 1.0),
    )


@app.post(
    "/ticks",
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(verify_api_key)],
    tags=["Data Feed"],
    summary="Ingest Bar/Tick Feature Snapshot",
)
async def post_ticks(payload: TickIn):
    pool = get_pool()
    try:
        async with pool.acquire() as conn:
            await conn.execute(
                """
                INSERT INTO tick_telemetry
                (asset, bid, ask, tick_volume, rsi, tema, ac, sar, adx, ma10, ma20, ma50, ma100, ma200, ts)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, NOW())
                """,
                payload.asset, payload.bid, payload.ask, payload.tick_volume, payload.rsi,
                payload.tema, payload.ac, payload.sar, payload.adx, payload.ma10, payload.ma20,
                payload.ma50, payload.ma100, payload.ma200,
            )
    except Exception:
        logger.exception("Failed to insert tick_telemetry row for %s", payload.asset)
        raise HTTPException(status_code=500, detail="Failed to store tick.")
    return {"status": "created", "asset": payload.asset}


@app.post(
    "/telemetry",
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(verify_api_key)],
    tags=["Telemetry"],
    summary="Log Trade Execution Telemetry",
)
async def post_telemetry(payload: TelemetryIn):
    pool = get_pool()
    try:
        async with pool.acquire() as conn:
            await conn.execute(
                """
                INSERT INTO trade_telemetry
                (asset, type, price, lots, profit, rsi, entry_score, sl_price, tp_price, magic_number, account_type, session_hour, forecast_id, ts)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, NOW())
                """,
                payload.asset, payload.type, payload.price, payload.lots, payload.profit,
                payload.rsi, payload.entry_score, payload.sl_price, payload.tp_price,
                payload.magic_number, payload.account_type, payload.session_hour, payload.forecast_id,
            )
    except Exception:
        logger.exception("Failed to insert trade_telemetry row for %s", payload.asset)
        raise HTTPException(status_code=500, detail="Failed to store telemetry.")
    return {"status": "logged", "asset": payload.asset}